### ISSUE TITLE
Only github trending would be sent for all kinds of events

### ISSUE THREAD

**Issue by ziming-zh** [junka/feishu-bot-webhook-action#1]
Hi @junka, thanks for the great work!

I've tested your workflow on v.1.0.7 and it seems that for now only github trending would be sent for all kinds of events (e.g. push, star repos). I wonder if that is expected behavior. If not, can you hint on how to fix that issue? Thanks!

Ziming

**Comment by junka** [comment]
Hi @ziming-zh 

Thanks for your interest and thanks for your report. 
Have a quick glance, it is a line for test that I add here for the github trending. Just remove it. 
[L83 context.eventName = "schedule"](https://github.com/junka/feishu-bot-webhook-action/blob/24fbb160106ca13e133367c5cce1986d5f0e0650/index.ts#L83C1-L83C35)

Remider, besides github trending, only star and push event are implmented really for construct a feishu card msg.

**Comment by ziming-zh** [comment]
Hi @junka, thanks for your prompt feedback!

It seems that the current push and star functionality still has some problem. You can see the difference from v1.0.7 and v1.0.8 after removing the hardcoded schedule events.

- v1.0.7

`push
{"StatusCode":0,"StatusMessage":"success","code":0,"data":{},"msg":"success"}`

- v1.0.8

`push
{"code":9499,"msg":"Bad Request","data":{}}`

Also for the star event:

`{"code":11246,"data":{},"msg":"msg: template not visible to app, code: 200381"}`

**Comment by junka** [comment]
Hi @ziming-zh 

My bad, did not test it.

> Hi @junka, thanks for your prompt feedback!
> 
> It seems that the current push and star functionality still has some problem. You can see the difference from v1.0.7 and v1.0.8 after removing the hardcoded schedule events.
> 
> * v1.0.7
> 
> `push {"StatusCode":0,"StatusMessage":"success","code":0,"data":{},"msg":"success"}`
> 
> * v1.0.8
> 
> `push {"code":9499,"msg":"Bad Request","data":{}}`

I should concat the message title for this. A bug here.

> 
> Also for the star event:
> 
> `{"code":11246,"data":{},"msg":"msg: template not visible to app, code: 200381"}`
There is a setting for the visibility of feishu card message. Now I have allow anybody the use the card.

I believe at least for now, you can see these two events in feishu.

**Comment by junka** [comment]
> Yes, it works now. Thank you for the great work. One small suggestion is to put the commit message inside the namecard. Currently we seem to have only commit id displayed

Sure, will do.

**Comment by junka** [comment]
update with commit:
https://github.com/junka/feishu-bot-webhook-action/commit/0c904a4823f0a245c87d120d1ad71b1d3e577df2

Close for this issue
