### ISSUE TITLE
Github Trending消息无法隐藏

### ISSUE THREAD

**Issue by Match-Yang** [junka/feishu-bot-webhook-action#4]
<img width="361" alt="image" src="https://github.com/junka/feishu-bot-webhook-action/assets/5242852/b16611f0-a420-46ab-8575-08483f9d7eb5">

请问如何关掉Github Trending？

**Comment by junka** [comment]
在workflow里面去掉对schedule事件的关注

**Comment by Match-Yang** [comment]
好的谢谢
